### ISSUE TITLE
10x visium x2 (H&E image) analysis using DeepTalk

### ISSUE THREAD

**Issue by GexinLiu** [JiangBioLab/DeepTalk#6]
Hello DeepTalk team,

You developed a good tool. I am reaching out as I am currently faced with a problem when attempting to analyze my own 10x Visium X2 (H&E image) data using DeepTalk, following the guidelines in your “Tutorial for cell-cell communication prediction for non-single-cell ST data with DeepTalk” introduction. 

However, during my attempts, I encountered difficulties when processing and segmenting my images using the functions ‘squidpy.im.process’ and ‘squidpy.im.segment’. Upon further inspection, it occurred to me that you used DAPI images in your tutorial documentation. Could you possibly provide advice, tips, or any resources that would be helpful in addressing the use of H&E images specifically with DeepTalk for effective data analysis?

Thanks.

**Comment by OMIC-coding** [comment]
Hello, GexinLiu, maybe you can check this~:
https://squidpy.readthedocs.io/en/stable/notebooks/examples/image/compute_segment_hne.html
Are you applying deeptalk on human data or mouse data?

**Comment by GexinLiu** [comment]
> Hello, GexinLiu, maybe you can check this~: https://squidpy.readthedocs.io/en/stable/notebooks/examples/image/compute_segment_hne.html Are you applying deeptalk on human data or mouse data?

Thanks for your reply. I will check the document and try again. I'm trying to apply DeepTalk on human data.
